### ISSUE TITLE
Metoda de calcul al entropiei totale al setului nostru de date

### ISSUE THREAD

**Issue by costin1995** [costin1995/DM_Gr1#11]
Sa se scrie o metoda care sa calculeze entropia globala a setului nostru de datele.
Pentru asta:
	- Construieste repartitia pe clase (cate articole au clasa a, cate au clasa b, etc) si o salveaza intr-un dictionar 
	- apeleaza metoda generica de calcul al entropiei cu dictionarul creat anterior si numarul total de articole

**Comment by CojocaruLiviuGabriel** [comment]
Buna ziua, in caz ca apar mai multe clase ( de exemplu "# C22 C31 CCAT # testing" ), in dictionar adaugam doar prima clasa sau toate?

**Comment by costin1995** [comment]
Salut, luam in considerare doar prima clasa
